name: health_home_care
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  awesome_icons: ^1.0.0
  cupertino_icons: ^1.0.2
  #dartz: ^0.10.1
  date_time_picker: ^2.1.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^5.0.0+1
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  loading_animations: ^2.2.0
  path_provider: ^2.0.8
  rflutter_alert: ^2.0.4
  sembast: ^3.1.1+1
  stacked: ^2.2.7+1
  stacked_generator: ^0.5.6
  stacked_services: ^0.8.16
  syncfusion_flutter_signaturepad: ^19.4.54
  hive: ^2.0.6
  hive_generator: ^1.1.2
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true
  
  assets:
    - assets/images/